AllCops:
  TargetRubyVersion: 3.4.4
  NewCops: enable

require:
  - rubocop-rspec
  - rubocop-rake

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 25

Metrics/ModuleLength:
  Max: 150

Style/Documentation:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false
